
/**

@provable automatic
@statistic nodes 151
@statistic branches 4
@see <a href="http://java.sun.com/docs/books/jls/third_edition/html/exceptions.html#11.3">Handling of an Exception (JLS, Sect. 11.3)</a>
@author Sebastian Wirkert (doc)

Demonstrates the symbolic execution of a try-catch-finally block. 
Inside the try-block a <tt>NullPointerException</tt> is thrown. It is caught
by the first catch clause. After the execution of the catch clause is
finished, the finally clause will be executed. Although
<tt>RuntimeException</tt> is a superclass of <tt>NullPointerException</tt>, it
will not be executed in the example, as only the first matching catch
clause is entered.

*/

\settings {"[StrategyProperty]METHOD_OPTIONS_KEY=METHOD_EXPAND"}

\programVariables {
  int i;
}


\problem { wellFormed(heap) ->
\<{
   i =0;
   try {
     throw null;
     i=2;
   }  catch (NullPointerException e0) {
     i=3;
   }  catch (RuntimeException e1) {
     i=5;
   }  finally {
     i=4;
   }
 }\> i = 4

}

